configuration:
    color:
        primary: green
        secondary: aqua
    logging:
        verbose: false
    factory:
        player: me.dbstudios.solusrpg.entities.player.SimpleRpgPlayer
        rpg-class: me.dbstudios.solusrpg.entities.SimpleRpgClass
        channel-logger: me.dbstudios.solusrpg.chat.SimpleChannelLogger
        aux-stat: me.dbstudios.solusrpg.entities.stats.SimpleAuxStat;
chat:
    enabled: true
    # Valid channel names are either:
    #   - the fully-qualified "GlobalChannel" variant
    #   - The display name of the channel (i.e. "Global" or "Server Announcements")
    #
    # Configurations for each will be found using the following:
    #   Spaces and special characters (as matched by /[_,.-]/) will be stripped ("Server Accouncements" -> "ServerAnnouncements")
    #   If the name does not end with "Channel" (case sensitive)...
    #       Append "Channel" to the name ("Gobal" -> "GlobalChannel")
    #   The channels directory (%rootdir%/config/channels/) is examined for ChannelName.yml ("GlobalChannel.yml")
    #   If a configuration is not found, an error will be emitted and Solus will proceed to the next entry
    channels:
        - Global
        - Whisper
        - Local
        - Yell
classes:
    # Valid class names are either:
    #   - The fully-qualified "KnightClass" variant
    #   - The display name of the class (i.e. "Light Mage")
    #
    # Configurations for each will be found using the following:
    #   Spaces will be stripped ("Light Mage" -> "LightMage")
    #   If the name does not end in "Class" (case sensitive)...
    #       Append "Class" to the name ("LightMage" -> "LightMageClass")
    #   The classes directory (%rootdir%/config/classes/) is examined for ClassName.yml ("LightMageClass.yml")
    #   If a configuration is not found, an error will be emitted and Solus will proceed to the next entry
    #
    # Any class under the enabled section will be loaded as publicly available. This means that
    # if a player is ever given the option to select their class (for example, when Solus creates their
    # player data) they will be able to select the class as their own.
    enabled:
        - Knight
        - Paladin
        - Thief
        - Necromancer
        - Light Mage
aux-stats:
    # Valid auxiliary stat names are either:
    #   - The fully-qualified "LightWeaponMasteryStat" variant
    #   - The display name of the stat (i.e. "Light Weapon Mastery")
    #
    # Configurations for each will be found using the following:
    #   Spaces and special characters (as matched by /[_,.-]/) will be stripped ("Light Weapon Mastery" -> "LightWeaponMastery")
    #   If the name does not end in "Stat" (case sensitive)...
    #       Append "Stat" to the name ("LightWeaponMastery" -> "LightWeaponMasteryStat")
    #   The stats directory (%rootdir%/config/stats/) is examined for StatName.yml ("LightWeaponMasteryStat.yml")
    #   If a configuration is not found, an error will be emitted and Solus will proceed to the next entry
    enabled:
        - Light Weapon Mastery
        - Heavy Weapon Mastery
        - Light Armor Mastery
        - Heavy Armor Mastery
leveling:
    # The experience algorithm will always receive the player's level as a variable called "level".
    # This variable can be freely placed anywhere in the algorithm.
    #
    # Default algorithm adapted from the information here: http://minecraft.gamepedia.com/Experience#Formulas_and_Tables
    #
    # For more information on this, and all of SolusRpg's mathematical functions, please visit https://github.com/LartTyler/SolusRpg/wiki/Expressions-System.
    global-level-cost: if(level <= 15, 17 * level, if(between(level, 16, 30), 1.5 * level^2 - 29.5 * level + 360, 3.5 * level^2 - 151.5 * level + 2220))