system:
    player-init:
        kick-data-dir-not-writeable: "Oh no! A configuration on the server prevented your player data from being created :( Please contact your server administrator!"
server:
    player-join-message: "{green}{player} {aqua}has joined the server."
    player-quit-message: "{green}{player} {aqua}has disconnected."