package me.dbstudios.solusrpg.util.siml;

public enum ConsumerState {
	DATA,
	TAG_OPEN,
	TAG_NAME,
	SELF_CLOSING_TAG,
	BEFORE_ATTRIBUTE_NAME,
	ATTRIBUTE_NAME,
	AFTER_ATTRIBUTE_NAME,
	BEFORE_ATTRIBUTE_VALUE,
	ATTRIBUTE_VALUE_QUOTED,
	ATTRIBUTE_VALUE_UNQUOTED,
	AFTER_ATTRIBUTE_VALUE,
	END_TAG_OPEN,
	EOF;
}